config/routes.rb
Rails.application.routes.draw do
  controller :products do
    get '/', action: :index, as: :index
  end

  resources :products, path: '/produtos'
  resources :available_products, path: '/detalhes', only: [:index, :new, :create]
end

app/models/available_product.rb
class AvailableProduct < ActiveRecord::Base
end

app/models/color.rb
class Color < ActiveRecord::Base
  validates :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :colors, join_table: :available_products
  has_and_belongs_to_many :sizes, join_table: :available_products

  validates :name, presence: true
  validates :description, presence: true
end

app/models/size.rb
class Size < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/available_products_controller.rb
class AvailableProductsController < ApplicationController
  def new
    @available = AvailableProduct.new
    @products = Product.all
    @colors = Color.all
    @sizes = Size.all
  end

  def create
    @product = ::Operations::AvailableProduct::Create.perform(available_product_params)

    render json: @product
    return

    redirect_to '/'
  end

  private

  def available_product_params
    params.required(:available_product).permit :colors => [ :id ], :products => [ :id ], :sizes => [ :id ]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product \
                .select('products.*', 'colors.name as color', 'sizes.name as size', 'count(*) as total')
                .joins(:colors, :sizes)
                .group('products.id', 'colors.id', 'sizes.id').all
  end

  def new
    @product = Product.new
    @colors = Color.all
    @sizes = Size.all
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = ::Operations::Product::Create.perform(product_params, product_params[:colors][:id], product_params[:sizes][:id])

    redirect_to '/'
  end

  def update
    @product = ::Operations::Product::Update.perform(params[:id], product_params)

    redirect_to '/'
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
 
    redirect_to '/'
  end

  private

  def product_params
    params.required(:product).permit :name, :description, :colors => [ :id ], :sizes => [ :id ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/available_products/new.html.erb
<div class="container">
  <%= simple_form_for @available do |f| %>
    <div class="row">
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.simple_fields_for :products do |c| %>
            <%= c.input :id, :collection => @products, :input_html => { :class => 'form-control' } %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.simple_fields_for :colors do |c| %>
            <%= c.input :id, :collection => @colors, :input_html => { :class => 'form-control' } %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.simple_fields_for :sizes do |c| %>
            <%= c.input :id, :collection => @sizes, :input_html => { :class => 'form-control' } %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-12">
        <%= f.button :submit, :class => 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teste Synergia Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Teste Rails</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="<%= new_product_path %>">Cadastrar Produto</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_available_product_path %>">Cadastrar Detalhes do Produto</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <div class="container-fluid">
    <div class="row">
      <%= yield %>
    </div>
  </div>


</body>
</html>

app/views/products/edit.html.erb
<div class="container">
  <h2>Editar Produto <%= @product.name %></h2>
  <%= simple_form_for @product do |f| %>
    <div class="row">
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.input :name, :input_html => { :class => 'form-control' } %>
        </div>
      </div>
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.input :description, :input_html => { :class => 'form-control' } %>
        </div>
      </div>
      <div class="col-sm-12">
        <%= f.button :submit, :class => 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Descrição</th>
              <th>Cor</th>
              <th>Tamanho</th>
              <th>Total</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @products.each do |prod| %>
              <tr>
              <td><%= prod.name %></td>
              <td><%= prod.description %></td>
              <td><%= prod.color %></td>
              <td><%= prod.size %></td>
              <td><%= prod.total %></td>
              <td>
                <%= link_to 'Deletar', product_path(prod),
                  method: :delete,
                  class: 'btn btn-danger btn-sm',
                  data: { confirm: 'Deseja realmente deletar?' }
                %>
                <%= link_to 'Editar', edit_product_path(prod), class: 'btn btn-primary btn-sm' %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

app/views/products/new.html.erb
<div class="container">
  <h2>Novo Produto</h2>
  <%= simple_form_for @product do |f| %>
    <div class="row">
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.input :name, :input_html => { :class => 'form-control' } %>
        </div>
      </div>
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.input :description, :input_html => { :class => 'form-control' } %>
        </div>
      </div>
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.simple_fields_for :colors do |c| %>
            <%= c.input :id, :collection => @colors, :input_html => { :class => 'form-control' } %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.simple_fields_for :sizes do |c| %>
            <%= c.input :id, :collection => @sizes, :input_html => { :class => 'form-control' } %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-12">
        <%= f.button :submit, :class => 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>